"""minha mudanca

Revision ID: 093eb6f2f489
Revises: 1ba56984b16f
Create Date: 2026-05-08 00:41:22.114767

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093eb6f2f489'
down_revision = '1ba56984b16f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

