"""test autogenerate

Revision ID: 16fb3981ca9a
Revises: 9900fd0ced61
Create Date: 2026-05-08 00:39:29.507529

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fb3981ca9a'
down_revision = '9900fd0ced61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

