"""minha mudanca

Revision ID: 1ba56984b16f
Revises: 16fb3981ca9a
Create Date: 2026-05-08 00:41:07.561607

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba56984b16f'
down_revision = '16fb3981ca9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

